INSERT INTO FILME (NOME. GENERO) VALUES('Persepolis','Drama');
INSERT INTO FILME (NOME. GENERO) VALUES('The Conjuring','Horror');
INSERT INTO FILME (NOME. GENERO) VALUES('Les Misérables','Musical');
INSERT INTO FILME (NOME. GENERO) VALUES('Blade Runner 2049','Action');
INSERT INTO FILME (NOME. GENERO) VALUES('Last Holiday','Comedy');
INSERT INTO FILME (NOME. GENERO) VALUES('Bacurau','Adventure');    
INSERT INTO FILME (NOME. GENERO) VALUES('Le fabuleux destin d Amélie Poulain','Romance');
INSERT INTO FILME (NOME. GENERO) VALUES('Gladiator','Action');
INSERT INTO FILME (NOME. GENERO) VALUES('Joker','Drama');
INSERT INTO FILME (NOME. GENERO) VALUES('The Matrix','Sci-Fi');
INSERT INTO FILME (NOME. GENERO) VALUES('Joker','Drama');
INSERT INTO FILME (NOME. GENERO) VALUES('Scott Pilgrim vs. the World','Action');
INSERT INTO FILME (NOME. GENERO) VALUES('Whiplash','Drama');    
INSERT INTO FILME (NOME. GENERO) VALUES('Inception','Sci-Fi');
INSERT INTO FILME (NOME. GENERO) VALUES('The Art of Racing in the Rain','Romance');
INSERT INTO FILME (NOME. GENERO) VALUES('A Clockwork Orange','Drama');
INSERT INTO FILME (NOME. GENERO) VALUES('Finding Forrester','Drama');
INSERT INTO FILME (NOME. GENERO) VALUES('Le huitième jour','Drama');
INSERT INTO FILME (NOME. GENERO) VALUES('Gisaengchung','Thriller');    
INSERT INTO FILME (NOME. GENERO) VALUES('The Neon Demon','Horro');
INSERT INTO FILME (NOME. GENERO) VALUES('Blow','Crime');
INSERT INTO FILME (NOME. GENERO) VALUES('Constantine','Action');
INSERT INTO FILME (NOME. GENERO) VALUES('12 Strong','Action');
INSERT INTO FILME (NOME. GENERO) VALUES('Seven Pounds','Drama');    
INSERT INTO FILME (NOME. GENERO) VALUES('Kimi no na wa.','Drama');
INSERT INTO FILME (NOME. GENERO) VALUES('Love Simon','Romance');
INSERT INTO FILME (NOME. GENERO) VALUES('Interstellar','Sci-Fi');
INSERT INTO FILME (NOME. GENERO) VALUES('Baby Driver','Action');
INSERT INTO FILME (NOME. GENERO) VALUES('Scarface','Drama');    
INSERT INTO FILME (NOME. GENERO) VALUES('Ratatouille','Adventure');
INSERT INTO FILME (NOME. GENERO) VALUES('Dances with Wolves','Western');
INSERT INTO FILME (NOME. GENERO) VALUES('It Chapter Two','Horror');
INSERT INTO FILME (NOME. GENERO) VALUES('Avengers: Endgame','Action');
INSERT INTO FILME (NOME. GENERO) VALUES('Pulp Fiction','Drama');    
INSERT INTO FILME (NOME. GENERO) VALUES('Dragon Ball Super: Doragon bôru cho','Action');
INSERT INTO FILME (NOME. GENERO) VALUES('Return to the Blue Lagoon','Romance');
INSERT INTO FILME (NOME. GENERO) VALUES('Fury','Drama');
INSERT INTO FILME (NOME. GENERO) VALUES('Hacksaw Ridge','Drama');
INSERT INTO FILME (NOME. GENERO) VALUES('Gravity','Sci-Fi');    
INSERT INTO FILME (NOME. GENERO) VALUES('Sharknado','Comedy');
INSERT INTO FILME (NOME. GENERO) VALUES('The Lord of the Rings: The Fellowship of the Ring','Adventure');
INSERT INTO FILME (NOME. GENERO) VALUES('Avengers: Endgame','Action');
INSERT INTO FILME (NOME. GENERO) VALUES('Joker','Drama');
INSERT INTO FILME (NOME. GENERO) VALUES('It Chapter Two','Horror');
INSERT INTO FILME (NOME. GENERO) VALUES('The Fast and the Furious','Action');    
INSERT INTO FILME (NOME. GENERO) VALUES('The Matrix','Sci-Fi');
INSERT INTO FILME (NOME. GENERO) VALUES('Shooter','Action');
INSERT INTO FILME (NOME. GENERO) VALUES('The Simpsons','Comedy');
INSERT INTO FILME (NOME. GENERO) VALUES('Star Wars: The Clone Wars','Action');
INSERT INTO FILME (NOME. GENERO) VALUES('Kimi no na wa.','Drama');
